routes/web.php
<?php

use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('role', RoleController::class);
Route::post('/role/store', [RoleController::class, 'store']);

Route::resource('user', UserController::class);

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/pegawai', [App\Http\Controllers\PegawaiController::class, 'index'])->name('pegawai');
Route::post('/pegawai', [App\Http\Controllers\PegawaiController::class, 'create'])->name('pegawai.create');
Route::get('/pegawai/getDatatable', [App\Http\Controllers\PegawaiController::class, 'getDatatable'])->name('pegawai.getDatatable');
Route::post('/pegawai/change-password/{id}', [App\Http\Controllers\PegawaiController::class, 'change_password'])->name('pegawai.change_password');
Route::get('/pegawai/{id}', [App\Http\Controllers\PegawaiController::class, 'show'])->name('pegawai.show');
Route::put('/pegawai/{id}', [App\Http\Controllers\PegawaiController::class, 'update'])->name('pegawai.update');
Route::delete('/pegawai/{id}', [App\Http\Controllers\PegawaiController::class, 'delete'])->name('pegawai.delete');

Route::get('/barang', [App\Http\Controllers\BarangController::class, 'index'])->name('barang');
Route::post('/barang', [App\Http\Controllers\BarangController::class, 'create'])->name('barang.create');
Route::get('/barang/getDatatable', [App\Http\Controllers\BarangController::class, 'getDatatable'])->name('barang.getDatatable');
Route::post('/barang/change-password/{id}', [App\Http\Controllers\BarangController::class, 'change_password'])->name('barang.change_password');
Route::get('/barang/{id}', [App\Http\Controllers\BarangController::class, 'show'])->name('barang.show');
Route::put('/barang/{id}', [App\Http\Controllers\BarangController::class, 'update'])->name('barang.update');
Route::delete('/barang/{id}', [App\Http\Controllers\BarangController::class, 'delete'])->name('barang.delete');

Route::get('/bagian', [App\Http\Controllers\BagianController::class, 'index'])->name('bagian');
Route::post('/bagian', [App\Http\Controllers\BagianController::class, 'create'])->name('bagian.create');
Route::get('/bagian/getDatatable', [App\Http\Controllers\BagianController::class, 'getDatatable'])->name('bagian.getDatatable');
Route::post('/bagian/change-password/{id}', [App\Http\Controllers\BagianController::class, 'change_password'])->name('bagian.change_password');
Route::get('/bagian/{id}', [App\Http\Controllers\BagianController::class, 'show'])->name('bagian.show');
Route::put('/bagian/{id}', [App\Http\Controllers\BagianController::class, 'update'])->name('bagian.update');
Route::delete('/bagian/{id}', [App\Http\Controllers\BagianController::class, 'delete'])->name('bagian.delete');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/role.blade.php
<!DOCTYPE html>
<html>

<head>
  <title>Tugas Binus</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
  <h3>List Role</h3>

  <a class="btn btn-success btn-sm" href="/role/create"> + Tambah Role </a>

  <br />
  <br />
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <tr>
        <th>No</th>
        <th>Nama</th>
        <th>Keterangan</th>
        <th>Aksi</th>
      </tr>
      @foreach ($role as $key => $r)
        <tr>
          <td>{{ ++$key }}</td>
          <td>{{ $r->nama_role }}</td>
          <td>{{ $r->keterangan }}</td>
          <td>
            <form action="{{ route('role.destroy', $r->id_role) }}" method="POST">
              <a type="button" class="btn btn-warning" href="{{ route('role.edit', $r->id_role) }}">Edit</a>
              @csrf
              @method('DELETE')
              <button type="submit" class="btn btn-danger">Hapus</button>
            </form>
          </td>
        </tr>
      @endforeach
    </table>
  </div>

</body>

</html>

resources/views/role_create.blade.php
<!DOCTYPE html>
<html>

<head>
  <title>Binus TP2</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>

<body>

  <nav class="navbar navbar-light bg-light justify-content-between">
    <a class="navbar-brand">TAMBAH DATA ROLE</a>
  </nav>

  <div class="container">
    <form action="/role/store" method="post" enctype="multipart/form-data">
      {{ csrf_field() }}
      <div class="col">
        Nama Role <input class="form-control" type="text" name="nama_role" placeholder="Nama Role"
          required="required"> <br />
      </div>
      <div class="col">
        Keterangan
        <textarea class="form-control" placeholder="Keterangan" name="keterangan"></textarea><br />
      </div>
      <input class="btn btn-success btn-sm" type="submit" value="Simpan Data">
      <a class="btn btn-warning btn-sm" href="/role">Batal</a>
    </form>
  </div>

</body>

</html>

resources/views/role_edit.blade.php
<!DOCTYPE html>
<html>

<head>
  <title>Binus TP2</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>

<body>

  <nav class="navbar navbar-light bg-light justify-content-between">
    <a class="navbar-brand">EDIT ROLE</a>
  </nav>

  <div class="container">
    <form action="{{ route('role.update', $role->id_role) }}" method="POST">
      @csrf
      @method('PUT')
      <input type="hidden" name="id_role" value="{{ $role->id_role }}"><br>
      <div class="col">
        Nama Role <input class="form-control" type="text" name="nama_role" placeholder="Tulis Nama Role"
          required="required" value="{{ $role->nama_role }}"> <br />
      </div>
      <div class="col">
        Keterangan
        <textarea class="form-control" name="keterangan">{{ $role->keterangan }}</textarea><br />
      </div>
      <input class="btn btn-success btn-sm" type="submit" value="Simpan Data">
      <a class="btn btn-warning btn-sm" href="/role">Batal</a>
    </form>
  </div>

</body>

</html>

resources/views/user.blade.php
<!DOCTYPE html>
<html>

<head>
  <title>Binus TP2</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
  <h3>User</h3>

  <a class="btn btn-success btn-sm" href="/user/create"> + Tambah User </a>

  <br />
  <br />
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <tr>
        <th>No</th>
        <th>Nama Lengkap</th>
        <th>Email</th>
        <th>Tanggal Lahir</th>
        <th>Jenis Kelamin</th>
        <th>Alamat</th>
        <th>Telp.</th>
        <th>Role</th>
        <th>Aksi</th>
      </tr>
      @foreach ($users as $key => $u)
        <tr>
          <td>{{ ++$key }}</td>
          <td>{{ $u->nama_lengkap }}</td>
          <td>{{ $u->email_corporate }}</td>
          <td>{{ $u->tanggal_lahir }}</td>
          <td>{{ $u->jenis_kelamin }}</td>
          <td>{{ $u->alamat }}</td>
          <td>{{ $u->nomor_telepon }}</td>
          <td>{{ $u->id_role }}</td>
          <td>
            <form action="{{ route('user.destroy', $u->id_user) }}" method="POST">
              <a type="button" class="btn btn-warning" href="{{ route('user.edit', $u->id_user) }}">Edit</a>
              @csrf
              @method('DELETE')
              <button type="submit" class="btn btn-danger">Hapus</button>
            </form>
          </td>
        </tr>
      @endforeach
    </table>
  </div>

</body>

</html>

resources/views/user_create.blade.php
<!DOCTYPE html>
<html>

<head>
  <title>Binus Task</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>

<body>

  <nav class="navbar navbar-light bg-light justify-content-between">
    <a class="navbar-brand">TAMBAH DATA USER</a>
  </nav>

  <div class="container">
    <form action="{{ route('user.store') }}" method="post" enctype="multipart/form-data">
      @csrf
      <div class="col">
        Nama Lengkap <input class="form-control" type="text" name="nama_lengkap" placeholder="Nama Lengkap"
          required="required"> <br />
      </div>
      <div class="col">
        Email Corporate <input class="form-control" type="text" name="email_corporate" placeholder="Email Corporate"
          required="required"> <br />
      </div>
      <div class="col">
        Password <input class="form-control" type="password" name="password" placeholder="Password" required="required">
        <br />
      </div>
      <div class="col">
        Tanggal Lahir <input class="form-control" type="date" name="tanggal_lahir" placeholder="Tulis Tanggal Lahir"
          required="required"> <br />
      </div>
      <div class="col">
        Jenis Kelamin
        <select class="form-control" name="jenis_kelamin" required>
          <option value="L">Laki-Laki</option>
          <option value="P">Perempuan</option>
        </select>
        <br>
      </div>
      <div class="col">
        Alamat <input class="form-control" type="text" name="alamat" placeholder="Alamat" required="required">
        <br />
      </div>
      <div class="col">
        Telepon <input class="form-control" type="text" name="nomor_telepon" placeholder="Nomor Telepon"
          required="required">
        <br />
      </div>
      <div class="col">
        Role
        <select name="id_role" class="form-control" required>
          @foreach ($roles as $key => $r)
            <option value="{{ $r->id_role }}"> {{ $r->nama_role }}</option>
          @endforeach
        </select>
        <br />
      </div>
      <input class="btn btn-success btn-sm" type="submit" value="Simpan Data">
      <a class="btn btn-warning btn-sm" href="/user">Batal</a>
    </form>
  </div>

</body>

</html>

resources/views/user_edit.blade.php
<!DOCTYPE html>
<html>

<head>
  <title>Binus TP2</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>

<body>

  <nav class="navbar navbar-light bg-light justify-content-between">
    <a class="navbar-brand">EDIT USER</a>
  </nav>

  <div class="container">
    <form action="{{ route('user.update', $user->id_user) }}" method="post" enctype="multipart/form-data">
      @csrf
      @method('PUT')
      <div class="col">
        Nama Lengkap <input class="form-control" type="text" value="{{ $user->nama_lengkap }}" name="nama_lengkap"
          placeholder="Nama Lengkap" required="required"> <br />
      </div>
      <div class="col">
        Email Corporate <input class="form-control" type="text" value="{{ $user->email_corporate }}"
          name="email_corporate" placeholder="Email Corporate" required="required"> <br />
      </div>
      <div class="col">
        Password <input class="form-control" type="password" value="{{ $user->password }}" name="password"
          placeholder="Password" required="required">
        <br />
      </div>
      <div class="col">
        Tanggal Lahir <input class="form-control" type="date" value="{{ $user->tanggal_lahir }}" name="tanggal_lahir"
          placeholder="Tulis Tanggal Lahir" required="required"> <br />
      </div>
      <div class="col">
        Jenis Kelamin
        <select class="form-control" value="{{ $user->jenis_kelamin }}" name="jenis_kelamin" required>
          <option value="L">Laki-Laki</option>
          <option value="P">Perempuan</option>
        </select>
        <br>
      </div>
      <div class="col">
        Alamat <input class="form-control" type="text" value="{{ $user->alamat }}" name="alamat"
          placeholder="Alamat" required="required">
        <br />
      </div>
      <div class="col">
        Telepon <input class="form-control" type="text" value="{{ $user->nomor_telepon }}" name="nomor_telepon"
          placeholder="Nomor Telepon" required="required">
        <br />
      </div>
      <div class="col">
        Role
        <select value="{{ $user->id_role }}" name="id_role" class="form-control" required>
          @foreach ($roles as $key => $r)
            <option value="{{ $r->id_role }}"> {{ $r->nama_role }}</option>
          @endforeach
        </select>
        <br />
      </div>
      <input class="btn btn-success btn-sm" type="submit" value="Simpan Data">
      <a class="btn btn-warning btn-sm" href="/user">Batal</a>
    </form>
  </div>

</body>

</html>